"""Build a single self-contained HTML viewer of the IIDS state (issue #8,
ADR-023) — the same pattern as the sibling project VOLT's Digital Shadow
viewer: one HTML file, embedded data, no CDN dependency, generated by a
script from `mv_intelligent_industry_state`.

This is a *display* layer only (sec. 39, ADR-006: BI is not a calculation
engine) — every aggregate below is a `SUM`/`AVG`/`COUNT` over already-computed
columns, the same constraint `docs/powerbi/report_pages_spec.md` applies to
the Power BI model. The Power BI semantic model (ADR-016) is not replaced by
this: it remains the documented path once a licensed Power BI environment and
real live data are available; this HTML file is the practical, always-buildable
"alpha 0" deliverable in the meantime.

Usage::

    python3 -m scripts.build_html_viewer --out dist/start_iids_viewer.html
    python3 -m scripts.build_html_viewer --db-url sqlite:///real.db --label "Estrazione ERP 2026-09-16" --out out/viewer.html
"""
from __future__ import annotations

import argparse
import json
import pathlib
from datetime import datetime, timezone

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

from scripts.export_mv_intelligent_industry_state import DIMENSION_QUERIES, build_synthetic_engine
from src.product.sales.channel_concentration import compute_channel_concentration

ROOT = pathlib.Path(__file__).resolve().parents[1]
TEMPLATE_PATH = ROOT / "bi" / "html_viewer" / "template.html"
DATA_PLACEHOLDER = "/*__DATA__*/"

# OR3/UNISS (Piano di Sviluppo, Allegato 4) task titles — the "Edificio" tab is
# a structural placeholder for that partner's real data, not a fabricated
# building dataset. See ADR-023.
BUILDING_PLACEHOLDER_TASKS = [
    {"id": "3.1", "title": "Involucri edilizi ceramici performanti — prototipazione e monitoraggio"},
    {"id": "3.2", "title": "Parametri ambientali di confort indoor"},
    {"id": "3.3", "title": "Controllo predittivo per involucri ventilati (deep learning)"},
    {"id": "3.4", "title": "Multiperformance e ottimizzazione del prodotto ceramico da involucro"},
]


def _avg(values: list[float]) -> float | None:
    values = [v for v in values if v is not None]
    return round(sum(values) / len(values), 4) if values else None


def build_payload(engine: Engine, *, dataset_label: str, data_note: str) -> dict:
    with engine.connect() as conn:
        rows = [dict(r) for r in conn.execute(text("SELECT * FROM mv_intelligent_industry_state")).mappings().all()]
        dims = {
            name: [dict(r) for r in conn.execute(text(query)).mappings().all()]
            for name, query in DIMENSION_QUERIES.items()
        }
        channel_sales_rows = conn.execute(text(
            "SELECT c.channel_id, c.channel_name, c.channel_type, SUM(s.sales_m2) AS sales_m2 "
            "FROM fact_product_sales s LEFT JOIN dim_distribution_channel c ON c.channel_id = s.channel_id "
            "GROUP BY c.channel_id, c.channel_name, c.channel_type"
        )).mappings().all()
        quality_rows = conn.execute(text(
            "SELECT severity, COUNT(*) AS n FROM audit_data_quality GROUP BY severity"
        )).mappings().all()

    # --- cluster aggregates (sec. 38.2 — client-side, but computed here in
    # Python so the HTML/JS layer stays a pure renderer, sec. 39) ---
    by_cluster: dict[tuple, dict] = {}
    for row in rows:
        key = (row.get("cluster_id"), row.get("cluster_version"))
        if key[0] is None:
            continue
        bucket = by_cluster.setdefault(key, {"p_tsi_5": [], "ioai": [], "opi": [], "tqi": [],
                                              "sales_m2": [], "trend_class": None})
        bucket["p_tsi_5"].append(row.get("p_tsi_5"))
        bucket["ioai"].append(row.get("ioai"))
        bucket["opi"].append(row.get("opi"))
        bucket["tqi"].append(row.get("tqi"))
        bucket["sales_m2"].append(row.get("sales_m2"))
        bucket["trend_class"] = row.get("cluster_trend") or bucket["trend_class"]
    clusters = [
        {
            "cluster_id": cluster_id, "cluster_version": cluster_version,
            "p_tsi_5_avg": _avg(v["p_tsi_5"]), "ioai_avg": _avg(v["ioai"]),
            "opi_avg": _avg(v["opi"]), "tqi_avg": _avg(v["tqi"]),
            "sales_m2_total": round(sum(x for x in v["sales_m2"] if x is not None), 2),
            "trend_class": v["trend_class"],
        }
        for (cluster_id, cluster_version), v in by_cluster.items()
    ]

    # --- distribution channel: real aggregation, sec. 38 known-gap style honesty (ADR-022) ---
    channel_sales = {r["channel_id"]: r["sales_m2"] or 0.0 for r in channel_sales_rows if r["channel_id"]}
    total_channel_sales = sum(channel_sales.values())
    channels = [
        {
            "channel_id": r["channel_id"], "channel_name": r["channel_name"], "channel_type": r["channel_type"],
            "sales_m2": r["sales_m2"] or 0.0,
            "share": round((r["sales_m2"] or 0.0) / total_channel_sales, 4) if total_channel_sales > 0 else None,
        }
        for r in channel_sales_rows if r["channel_id"]
    ]
    channel_hhi = compute_channel_concentration(channel_sales)

    quality = {r["severity"]: r["n"] for r in quality_rows}

    return {
        "meta": {
            "title": "START IIDS — Digital Shadow viewer",
            "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "generator": "scripts/build_html_viewer.py",
            "dataset_label": dataset_label,
            "data_note": data_note,
        },
        "kpi": {
            "tsi_norm_avg": _avg([r.get("tsi_norm") for r in rows]),
            "p_tsi_5_avg": _avg([r.get("p_tsi_5") for r in rows]),
            "data_quality_score_avg": _avg([r.get("data_quality_score") for r in rows]),
            "channel_concentration_hhi": channel_hhi,
            "record_count": len(rows),
            "record_count_with_tsi": sum(1 for r in rows if r.get("tsi_norm") is not None),
        },
        "dims": dims,
        "rows": rows,
        "clusters": clusters,
        "channels": channels,
        "quality": quality,
        "building_placeholder": BUILDING_PLACEHOLDER_TASKS,
    }


def render_html(payload: dict) -> str:
    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    if DATA_PLACEHOLDER not in template:
        raise ValueError(f"{TEMPLATE_PATH} is missing the {DATA_PLACEHOLDER} marker")
    data_json = json.dumps(payload, ensure_ascii=False, default=str)
    return template.replace(DATA_PLACEHOLDER, data_json)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db-url", default=None,
                         help="SQLAlchemy URL to build from. Omit to use the ephemeral "
                              "synthetic-seeded SQLite database (ADR-014).")
    parser.add_argument("--label", default=None,
                         help="Human-readable dataset provenance shown in the viewer's Build tab. "
                              "Required (and not defaulted) when --db-url is given, so provenance "
                              "is never silently guessed.")
    parser.add_argument("--out", type=pathlib.Path, default=pathlib.Path("dist/start_iids_viewer.html"))
    args = parser.parse_args()

    if args.db_url:
        if not args.label:
            parser.error("--label is required when --db-url is given (never guess data provenance)")
        engine = create_engine(args.db_url)
        dataset_label = args.label
        data_note = f"Dati da {args.db_url!r} — {args.label}."
    else:
        engine = build_synthetic_engine()
        dataset_label = "SYNTHETIC_DEMO (ADR-014)"
        data_note = ("Dataset sintetico e chiaramente etichettato (ADR-014) — non dati reali. "
                     "Nessun coefficiente/peso qui è mai da considerare APPROVED.")

    payload = build_payload(engine, dataset_label=dataset_label, data_note=data_note)
    html = render_html(payload)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(html, encoding="utf-8")
    print(f"Viewer written to {args.out} ({len(payload['rows'])} shadow-state rows, "
          f"{len(payload['clusters'])} clusters, {len(payload['channels'])} channels)")


if __name__ == "__main__":
    main()
